enable conversational mode, without hotword detection
evancohen/sonus pull request #102
Opened 2020-06-10 02:47 UTC by sdetweil

2020-06-10 20:31 UTC, evancohen requested changes

2020-06-10 20:31 UTC, evancohen commented on index.js
> -module.exports = Sonus
It's really hard to see what you did here with the diff like this. Make sure your line endings are set to as-is.
https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings

Once I can see the diff here I'll review :)

2020-06-10 21:11 UTC, sdetweil commented
I don't understand.. i got the prior commit, and manually merged my changes, 
editing on linux with linux line ends/ 
I added the git

2020-06-11 01:35 UTC, sdetweil commented
will redo

2020-06-11 01:35 UTC, closed without merging